// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ketrlwuqnjnzizzszovs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtldHJsd3Vxbmpueml6enN6b3ZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyMjgyODksImV4cCI6MjA0OTgwNDI4OX0.4NR9dtFrnfnKXqZzmGGN3bvKTHmUEuWE-gB-VEl_fzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);